version: '3.8'

services:
  wordpress:
    image: wordpress:php8.1-apache
    container_name: app_wordpress
    volumes:
      - ./htdocs:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html/wp
    restart: always
    ports:
      - "7402:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      TZ: Asia/Tokyo

  db:
    image: mysql:8.0
    container_name: mysql_wordpress
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306


  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    container_name: mailhog_wordpress
    ports:
      - '8025:8025'
      - '1025:1025'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin_wordpress
    links:
      - db
    ports:
      - '8000:80'
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
      - ./docker/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
